export default {
  darkMode: 'class',
  content: [
    './index.html',
    './App.tsx',
    './components/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './context/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
    './services/**/*.{js,ts,jsx,tsx}',
    './utils/**/*.{js,ts,jsx,tsx}',
    './data/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        serif: ['ui-serif', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
        sans: ['ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', '"Helvetica Neue"', 'Arial', 'sans-serif'],
      },
      colors: {
        brand: {
          dark: '#1A4D5C',
          primary: '#1A4D5C',
          medium: '#5D8494',
          light: '#F0F6F8',
          cream: '#F5F3F0',
          warmOffWhite: '#F5F3F0',
          surface: '#FFFFFF',
          darkBase: '#0F1419',
          darkSurface: '#1A1F28',
          darkBorder: '#2A3038',
          darkText: '#F5F5F5',
          darkTextMuted: '#A0A0A0',
          gold: '#D4A574',
          notificationTeal: '#24B4AC',
          goldMuted: '#C9A85D',
          goldLight: '#F3EAD3',
          coral: '#E8A87C',
          sage: '#9CAD9E',
          lavender: '#C4BFE0',
          midnight: '#0B1121',
          purple: '#C4BFE0',
          mint: '#EBF5F3',
          sunset: '#E8A87C',
          mutedTeal: '#2F4A4F',
          mutedSand: '#C6A27E',
          softMistBlue: '#E6F0F2',
          mutedGrey: '#8B9A9D',
          softBlueGrey: '#8FA5AA',
          lightNeutral: '#F4F7F8',
          offWhite: '#FAF8F4',
        }
      },
      boxShadow: {
        'glow-dark': '0 0 20px rgba(212, 165, 116, 0.15)',
      },
      backgroundImage: {
        'gradient-peacock': 'linear-gradient(135deg, #1A4D5C 0%, #2F5A6C 100%)',
        'gradient-dawn': 'linear-gradient(135deg, #F5F3F0 0%, #F0F6F8 100%)',
        'gradient-dusk': 'linear-gradient(135deg, #0B1121 0%, #1A4D5C 100%)',
        'gradient-gold': 'linear-gradient(135deg, #D4A574 0%, #E6C298 100%)',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 2.5s infinite linear',
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'float': 'float 3s ease-in-out infinite',
        'spin-slow': 'spin 12s linear infinite',
        'zen-dust': 'zenDust 1.5s ease-out forwards',
        'mascot-peek': 'mascotPeek 2s ease-in-out forwards',
        'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
        'firework': 'firework 1s ease-out forwards',
        'fall-slow': 'fall 3s ease-out forwards',
        'fly': 'fly 3s ease-in-out forwards',
        'sway': 'sway 3s ease-in-out infinite',
        'ripple': 'ripple 8s linear infinite',
        'gradient-shift': 'gradientShift 8s ease infinite',
        'pulse-checkmark': 'pulseCheckmark 2s ease-in-out infinite',
        'rise-up': 'riseUp 4s ease-out forwards',
        'scale-in': 'scaleIn 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'tap-pulse': 'tapPulse 2s ease-in-out infinite',
        'box-text-fade': 'boxTextFade 0.4s ease-out forwards',
        'box-morph': 'boxMorph 3s ease-in-out infinite',
        'box-particle-float': 'boxParticleFloat 2s ease-in-out infinite',
        'box-bg-gradient': 'boxBgGradient 12s ease-in-out infinite',
        'box-bg-particle': 'boxBgParticle 15s ease-in-out infinite',
        'prepare-card-pulse': 'prepareCardPulse 3s ease-in-out infinite',
        'prepare-card-scale-pulse': 'prepareCardScalePulse 3s ease-in-out infinite',
        'prepare-square-icon': 'prepareSquareIcon 2.5s ease-in-out infinite',
        'prepare-leaf-sway': 'prepareLeafSway 3s ease-in-out infinite',
        'prepare-flame-flicker': 'prepareFlameFlicker 1.2s ease-in-out infinite',
        'prepare-flame-card-pulse': 'prepareFlameCardPulse 3s ease-in-out infinite',
        'prepare-moon-glow-pulse': 'prepareMoonGlowPulse 3.5s ease-in-out infinite',
        'prepare-rest-card-pulse': 'prepareRestCardPulse 3.5s ease-in-out infinite',
        'prepare-scale-balance-tip': 'prepareScaleBalanceTip 2.5s ease-in-out infinite',
        'prepare-balance-card-pulse': 'prepareBalanceCardPulse 3s ease-in-out infinite',
        'countdown-dreamy-fade': 'countdownDreamyFade 1.2s ease-out forwards',
        'countdown-balance-fade': 'countdownBalanceFade 1.2s ease-out forwards',
        'countdown-pulse': 'countdownPulse 1s ease-in-out',
        'calm-wave-breathe': 'calmWaveBreathe 4s ease-in-out infinite',
        'calm-particle-rise': 'calmParticleRise 3s ease-out forwards',
        'calm-leaf-sway': 'calmLeafSway 4s ease-in-out infinite',
        'water-ripple': 'waterRipple 4s ease-out infinite',
        'twinkle': 'twinkle 3s ease-in-out infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        zenDust: {
          '0%': { opacity: '0', transform: 'translateY(0) scale(0)' },
          '50%': { opacity: '1' },
          '100%': { opacity: '0', transform: 'translateY(-60px) scale(1.5)' },
        },
        mascotPeek: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '20%': { transform: 'translateY(-10%)', opacity: '1' },
          '80%': { transform: 'translateY(-10%)', opacity: '1' },
          '100%': { transform: 'translateY(100%)', opacity: '0' },
        },
        firework: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(2.5)', opacity: '0' },
        },
        fall: {
          '0%': { transform: 'translateY(-10vh)', opacity: '0' },
          '10%': { opacity: '0.8' },
          '100%': { transform: 'translateY(60vh)', opacity: '0' },
        },
        fly: {
          '0%': { transform: 'translate(0, 0) scale(0.5)', opacity: '0' },
          '10%': { opacity: '1', transform: 'translate(0, 0) scale(1)' },
          '100%': { transform: 'translate(100vw, -20vh) scale(0.8)', opacity: '0' },
        },
        sway: {
          '0%, 100%': { transform: 'translateX(-10px) rotate(-10deg)' },
          '50%': { transform: 'translateX(10px) rotate(10deg)' },
        },
        ripple: {
          '0%': { transform: 'scale(0.8)', opacity: '0.1' },
          '50%': { opacity: '0.05' },
          '100%': { transform: 'scale(2.5)', opacity: '0' },
        },
        dash: {
          '0%': { strokeDashoffset: '0' },
          '100%': { strokeDashoffset: '6' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        pulseCheckmark: {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.1)', opacity: '0.9' },
        },
        riseUp: {
          '0%': { transform: 'translateY(0)', opacity: '0.8' },
          '100%': { transform: 'translateY(-120vh)', opacity: '0' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        tapPulse: {
          '0%, 100%': { opacity: '0.7' },
          '50%': { opacity: '1' },
        },
        boxTextFade: {
          '0%': { opacity: '1' },
          '50%': { opacity: '0.3' },
          '100%': { opacity: '1' },
        },
        boxMorph: {
          '0%, 100%': { transform: 'scale(1) rotate(0deg)' },
          '50%': { transform: 'scale(1.05) rotate(5deg)' },
        },
        boxParticleFloat: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.5' },
          '50%': { transform: 'scale(1.3)', opacity: '1' },
        },
        boxBgGradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        boxBgParticle: {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
          '25%': { transform: 'translate(3px, -4px) rotate(2deg)' },
          '50%': { transform: 'translate(-2px, 3px) rotate(-1deg)' },
          '75%': { transform: 'translate(4px, 2px) rotate(1deg)' },
        },
        prepareCardPulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.97' },
        },
        prepareCardScalePulse: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.02)' },
        },
        prepareLeafSway: {
          '0%, 100%': { transform: 'translateY(0) rotate(-3deg)' },
          '50%': { transform: 'translateY(-6px) rotate(3deg)' },
        },
        prepareFlameFlicker: {
          '0%, 100%': { transform: 'scale(1) translateY(0)', opacity: '1' },
          '25%': { transform: 'scale(1.08) translateY(-3px)', opacity: '0.95' },
          '50%': { transform: 'scale(0.95) translateY(2px)', opacity: '1' },
          '75%': { transform: 'scale(1.05) translateY(-2px)', opacity: '0.98' },
        },
        prepareFlameCardPulse: {
          '0%, 100%': { transform: 'scale(1)', boxShadow: '0 0 40px rgba(245,158,11,0.2), inset 0 0 60px rgba(245,158,11,0.02)' },
          '50%': { transform: 'scale(1.02)', boxShadow: '0 0 60px rgba(245,158,11,0.35), inset 0 0 80px rgba(245,158,11,0.04)' },
        },
        prepareMoonGlowPulse: {
          '0%, 100%': { opacity: '0.85', boxShadow: '0 0 12px rgba(129,140,248,0.3)' },
          '50%': { opacity: '1', boxShadow: '0 0 24px rgba(129,140,248,0.5)' },
        },
        prepareRestCardPulse: {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.015)', opacity: '0.98' },
        },
        countdownDreamyFade: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        prepareScaleBalanceTip: {
          '0%, 100%': { transform: 'rotate(-6deg)' },
          '50%': { transform: 'rotate(6deg)' },
        },
        prepareBalanceCardPulse: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.02)' },
        },
        countdownBalanceFade: {
          '0%': { opacity: '0', transform: 'translateX(-6px)' },
          '50%': { opacity: '0.6', transform: 'translateX(3px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        prepareSquareIcon: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.8' },
          '50%': { transform: 'scale(1.05)', opacity: '1' },
        },
        countdownPulse: {
          '0%': { transform: 'scale(1.1)', opacity: '1' },
          '50%': { transform: 'scale(1)', opacity: '0.9' },
          '100%': { transform: 'scale(1.1)', opacity: '1' },
        },
        calmWaveBreathe: {
          '0%, 100%': { backgroundPosition: '0% 0%' },
          '50%': { backgroundPosition: '0% 100%' },
        },
        calmParticleRise: {
          '0%': { transform: 'translateY(0)', opacity: '0.3' },
          '50%': { opacity: '0.6' },
          '100%': { transform: 'translateY(-100vh)', opacity: '0' },
        },
        calmLeafSway: {
          '0%, 100%': { transform: 'translateY(0) rotate(-5deg)' },
          '50%': { transform: 'translateY(-8px) rotate(5deg)' },
        },
        waterRipple: {
          '0%': { transform: 'scale(0.4)', opacity: '0.3' },
          '50%': { opacity: '0.08' },
          '100%': { transform: 'scale(2)', opacity: '0' },
        },
        twinkle: {
          '0%, 100%': { opacity: '0.18' },
          '50%': { opacity: '0.4' },
        },
      }
    }
  }
}
