import React, { useState, useEffect } from 'react';
import { ArrowLeft, Plus, Trash2, Sparkles, Calendar, Target, RefreshCw } from 'lucide-react';
import { BackButton } from '../components/BackButton';
import { useNavigate, useLocation } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { generateIntentionFromHoroscope } from '../services/astroApi';
import {
  createIntention,
  deleteIntention,
  getIntentionHistory,
  getTodayIntention,
  Intention
} from '../services/intentionApi';
import { motion } from 'framer-motion';

interface HoroscopeData {
  theme: string;
  description: string;
  doToday: string[];
  dontToday: string[];
}

const STORAGE_RESULT_PREFIX = 'daily_horoscope_result_v1_';
const getTodayDateISO = () => new Date().toISOString().slice(0, 10);

const HistorySkeleton = () => (
  <div className="space-y-3">
    {[1, 2, 3].map((i) => (
      <div
        key={i}
        className="bg-brand-lightNeutral dark:bg-brand-darkSurface/70 rounded-[21px] p-5 card-standard flex flex-col gap-3"
      >
        <div className="flex items-start justify-between gap-3">
          <div className="h-3 w-24 bg-gray-200 dark:bg-gray-700 rounded animate-pulse" />
          <div className="h-4 w-4 bg-gray-200 dark:bg-gray-700 rounded animate-pulse" />
        </div>
        <div className="flex gap-3 items-start">
          <div className="h-4 w-4 bg-gray-200 dark:bg-gray-700 rounded-full animate-pulse mt-0.5" />
          <div className="flex-1 space-y-2">
            <div className="h-3 w-full bg-gray-200 dark:bg-gray-700 rounded animate-pulse" />
            <div className="h-3 w-3/4 bg-gray-200 dark:bg-gray-700 rounded animate-pulse" />
          </div>
        </div>
      </div>
    ))}
  </div>
);

export const IntentionJournal: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { theme } = useApp();

  // Local state for intentions
  const [todayIntention, setTodayIntention] = useState<Intention | null>(null);
  const [history, setHistory] = useState<Intention[]>([]);
  const [loading, setLoading] = useState(true);

  // Horoscope data
  const suggestedIntention = (location.state as any)?.suggestedIntention || '';
  const fromHoroscope = (location.state as any)?.fromHoroscope || false;
  const horoscopeData = (location.state as any)?.horoscopeData as HoroscopeData | undefined;

  const [text, setText] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Helper to try and get intention from cached horoscope
  const getCachedHoroscopeIntention = (): string | null => {
      try {
          const todayKey = STORAGE_RESULT_PREFIX + getTodayDateISO();
          const cachedResult = localStorage.getItem(todayKey);
          if (cachedResult) {
              const parsed = JSON.parse(cachedResult);
              return parsed?.content?.intention || null;
          }
      } catch (e) {
          console.warn('Failed to retrieve cached horoscope intention', e);
      }
      return null;
  };

  // Load data on mount
  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      try {
        const [today, histData] = await Promise.all([
            getTodayIntention(),
            getIntentionHistory()
        ]);
        setTodayIntention(today);
        setHistory(histData.entries);

        // If we have a stored intention for today, populate the text field if empty
        if (today) {
          setText(today.content);
        } else {
            // Check if we have a suggested intention passed via state OR cached in horoscope
            const cachedIntention = suggestedIntention || getCachedHoroscopeIntention();
            if (cachedIntention) {
                setText(cachedIntention);
                setHasAutoGenerated(true); // Mark as auto-generated so we can trigger save
            }
        }
      } catch (err) {
        console.error('Failed to load intention data', err);
      } finally {
        setLoading(false);
      }
    };
    loadData();
  }, []);

  // Handle Horoscope flow: Auto-fill if coming from horoscope OR if we found a cached one
  // We do NOT auto-save anymore, we just pre-fill the text area for the user to decide.
  useEffect(() => {
    // Only proceed if we have text, no backend record yet, and not currently loading/generating
    if (text && !todayIntention && !loading && !isGenerating && hasAutoGenerated) {
       // We already set the text in the initial load useEffect.
       // We just ensure the user knows it's ready to be saved.
       // No automatic 'createIntention' call here.
    }
  }, [text, todayIntention, loading, isGenerating, hasAutoGenerated]);


  const handleGenerateIntention = async () => {
    if (!horoscopeData) return;
    if (todayIntention) return;

    setIsGenerating(true);
    try {
      const generated = await generateIntentionFromHoroscope(
        horoscopeData.theme,
        horoscopeData.description,
        horoscopeData.doToday,
        horoscopeData.dontToday
      );
      setText(generated);
      setHasAutoGenerated(true);
    } catch (error: any) {
      console.error('Failed to generate intention:', error);
      alert(error?.message || 'Failed to generate intention. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Auto-generate if horoscope data available but no intention yet
  useEffect(() => {
    if (horoscopeData && !hasAutoGenerated && !todayIntention && !suggestedIntention && !text && !loading) {
      setHasAutoGenerated(true);
      handleGenerateIntention();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [horoscopeData, hasAutoGenerated, todayIntention, suggestedIntention, loading]);


  const handleSave = async () => {
    const trimmed = text.trim();
    if (!trimmed) return;

    setIsSaving(true);
    try {
      const saved = await createIntention(trimmed, undefined, horoscopeData ? 'horoscope' : 'manual');
      setTodayIntention(saved);
      setText(saved.content); // Ensure text matches saved content
      
      // Refresh history
      const histData = await getIntentionHistory();
      setHistory(histData.entries);
    } catch (err) {
      console.error('Failed to save intention', err);
      alert('Failed to save intention. Please try again.');
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: string) => {
      if (!confirm('Are you sure you want to delete this intention?')) return;
      try {
          await deleteIntention(id);
          
          // Refresh data
          const [today, histData] = await Promise.all([
            getTodayIntention(),
            getIntentionHistory()
          ]);
          setTodayIntention(today);
          setHistory(histData.entries);
          if (!today) setText(''); // Clear text if today's intention was deleted
      } catch (err) {
          console.error('Failed to delete intention', err);
      }
  };

  const formatDate = (isoString: string) => {
    // Determine if the date string is UTC (ends with Z) or local
    // The backend stores YYYY-MM-DD which is timezone agnostic but usually treated as local date for the day
    // We can just parse it as local date parts
    const dateParts = isoString.split('T')[0].split('-');
    if (dateParts.length === 3) {
        const date = new Date(parseInt(dateParts[0]), parseInt(dateParts[1]) - 1, parseInt(dateParts[2]));
        return date.toLocaleDateString('en-US', {
            weekday: 'long',
            month: 'short',
            day: 'numeric',
        });
    }
    return new Date(isoString).toLocaleDateString('en-US', {
      weekday: 'long',
      month: 'short',
      day: 'numeric',
    });
  };

  const isTodayGenerated = !!todayIntention;

  return (
    <div
      className={`min-h-screen flex flex-col bg-gradient-to-b ${
        theme === 'dark'
          ? 'from-brand-darkBase via-[#0B1121] to-brand-midnight'
          : 'from-[#F5F0EA] via-[#F0EBE4] to-[#E8E6E0]'
      }`}
    >
      {/* Header */}
      <div className="relative z-12 px-6 pt-12 pb-4">
        <div className="flex items-center gap-3">
          <BackButton
            variant="adaptive"
            onClick={() => {
              if (fromHoroscope) {
                navigate('/horoscope-result');
              } else {
                navigate('/');
              }
            }}
          />
          <div className="flex flex-col">
            <h1 className="text-2xl font-serif font-medium text-brand-mutedTeal dark:text-white leading-none tracking-tight">
              Intention
            </h1>
            <p className="text-[10px] font-medium text-brand-mutedSand uppercase tracking-[0.2em] mt-1">
              Set Your Direction
            </p>
          </div>
        </div>
      </div>

      {/* Main content */}
      <div className="flex-1 flex flex-col px-4 pb-32 space-y-8 overflow-y-auto">
        {/* Hero Card - Today's Intention */}
        <motion.div 
          initial={{ opacity: 0, y: 6 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="relative w-full mx-auto"
        >
            <div className="absolute inset-0 bg-gradient-to-b from-[#F5F3F0] to-[#F0EDE8] dark:from-brand-darkSurface dark:to-brand-darkBase rounded-[21px] card-standard dark:shadow-none -z-10" />
            
            <div className="rounded-[21px] p-6 md:p-10 flex flex-col items-center justify-center text-center space-y-6 border border-white/40 dark:border-white/10">
                
                {/* Icon Area */}
                <div className="relative">
                    <motion.div
                        animate={{ 
                            boxShadow: ["0 0 20px rgba(198,162,126,0.15)", "0 0 35px rgba(198,162,126,0.35)", "0 0 20px rgba(198,162,126,0.15)"],
                            scale: [1, 1.03, 1]
                        }}
                        transition={{ 
                            duration: 4, 
                            repeat: Infinity, 
                            ease: "easeInOut" 
                        }}
                        className="w-16 h-16 rounded-full border border-brand-mutedSand/30 flex items-center justify-center bg-[#F5F3F0]/80 dark:bg-brand-darkSurface"
                    >
                        <Target size={24} className="text-brand-mutedSand" />
                    </motion.div>
                </div>

                {/* Label */}
                <p className="text-[11px] font-medium text-brand-mutedSand uppercase tracking-[0.25em]">
                    Today&apos;s Intention
                </p>

                {/* Main Text Area */}
                <div className="w-full max-w-full md:max-w-[90%]">
                    {isTodayGenerated ? (
                        <h2 className="text-2xl md:text-[26px] font-serif leading-[1.6] text-brand-mutedTeal dark:text-brand-darkText">
                            &ldquo;{text}&rdquo;
                        </h2>
                    ) : (
                        <textarea
                            value={text}
                            onChange={(e) => setText(e.target.value)}
                            disabled={isGenerating || isSaving}
                            rows={3}
                            placeholder="What is your focus for today?"
                            className="w-full bg-white/80 dark:bg-black/30 backdrop-blur-sm border border-brand-mutedSand/20 rounded-2xl p-4 text-center text-xl md:text-2xl font-serif leading-[1.6] text-brand-mutedTeal dark:text-brand-darkText placeholder:text-brand-mutedGrey/60 focus:outline-none focus:ring-2 focus:ring-brand-mutedSand/25 focus:border-brand-mutedSand/30 resize-none shadow-sm transition-all"
                        />
                    )}
                </div>

                {/* Divider */}
                <div className="flex items-center gap-4 w-full justify-center opacity-40">
                    <div className="h-[1px] w-12 bg-brand-mutedSand"></div>
                    <div className="w-1.5 h-1.5 rounded-full bg-brand-mutedSand"></div>
                    <div className="h-[1px] w-12 bg-brand-mutedSand"></div>
                </div>

                {/* Actions or Info */}
                {isTodayGenerated ? (
                    <p className="text-[13px] text-brand-mutedGrey/80 text-center max-w-xs leading-relaxed">
                        You&apos;ve already set your intention today. Come back tomorrow for a new reading.
                    </p>
                ) : (
                    <div className="w-full space-y-3 pt-2">
                        {horoscopeData && (
                             <button
                                onClick={handleGenerateIntention}
                                disabled={isGenerating}
                                className={`w-full py-3 rounded-xl font-medium text-xs uppercase tracking-widest flex items-center justify-center gap-2 transition-all ${
                                    isGenerating
                                    ? 'bg-brand-softMistBlue text-brand-mutedGrey cursor-wait'
                                    : 'bg-white border border-brand-mutedSand/30 text-brand-mutedSand hover:bg-brand-cream'
                                }`}
                            >
                                {isGenerating ? (
                                    <>
                                        <RefreshCw size={14} className="animate-spin" />
                                        Generating...
                                    </>
                                ) : (
                                    <>
                                        <Sparkles size={14} />
                                        Align with my Stars
                                    </>
                                )}
                            </button>
                        )}
                        
                        <button
                            onClick={handleSave}
                            disabled={!text.trim() || isGenerating || isSaving}
                            className={`w-full py-3.5 rounded-xl font-medium text-xs uppercase tracking-widest flex items-center justify-center gap-2 transition-all shadow-lg shadow-brand-mutedSand/20 ${
                            text.trim() && !isGenerating && !isSaving
                                ? 'bg-brand-mutedTeal text-white hover:bg-brand-primary active:scale-[0.98]'
                                : 'bg-brand-softMistBlue text-brand-mutedGrey cursor-not-allowed'
                            }`}
                        >
                            {isSaving ? (
                                <>
                                    <RefreshCw size={14} className="animate-spin" />
                                    Saving...
                                </>
                            ) : (
                                <>
                                    <Plus size={14} />
                                    Save Intention
                                </>
                            )}
                        </button>
                    </div>
                )}
            </div>
        </motion.div>

        {/* History Section */}
        <div className="space-y-4 pt-4">
          <div className="flex items-center gap-2 px-2 opacity-80">
            <Calendar size={14} className="text-brand-softBlueGrey" />
            <h3 className="text-[11px] font-medium text-brand-softBlueGrey uppercase tracking-[0.2em]">
              Past Intentions
            </h3>
          </div>

          {loading ? (
            <HistorySkeleton />
          ) : history.length === 0 ? (
            <div className="text-center py-12 opacity-40 text-sm italic font-serif text-brand-mutedGrey">
              Your journey of intention begins today.
            </div>
          ) : (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="space-y-3"
            >
              {history.map((entry) => (
                <div
                  key={entry.id}
                  className={`bg-brand-lightNeutral dark:bg-brand-darkSurface/70 rounded-[21px] p-6 border card-standard transition-all ${
                      entry.id === todayIntention?.id 
                      ? 'border-brand-mutedSand/50 shadow-sm' 
                      : 'border-transparent hover:border-brand-softMistBlue'
                  }`}
                >
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <p className="text-[10px] font-bold text-brand-mutedSand uppercase tracking-widest">
                        {formatDate(entry.date)}
                    </p>
                    <button
                      onClick={() => handleDelete(entry.id)}
                      className="text-brand-softBlueGrey hover:text-red-400 transition-colors opacity-60 hover:opacity-100"
                      aria-label="Delete intention"
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                  <p className="text-sm md:text-base text-brand-mutedTeal/90 dark:text-brand-darkText/90 leading-relaxed font-serif">
                      {entry.content}
                  </p>
                </div>
              ))}
            </motion.div>
          )}
        </div>
      </div>

    </div>
  );
};
